# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protobufs.grpc_change_index_pb2 as grpc__change__index__pb2


class ChangeIndexStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Change = channel.unary_unary(
                '/barband_change_index.ChangeIndex/Change',
                request_serializer=grpc__change__index__pb2.RequestToIndex.SerializeToString,
                response_deserializer=grpc__change__index__pb2.Response.FromString,
                )


class ChangeIndexServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChangeIndexServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=grpc__change__index__pb2.RequestToIndex.FromString,
                    response_serializer=grpc__change__index__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barband_change_index.ChangeIndex', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChangeIndex(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barband_change_index.ChangeIndex/Change',
            grpc__change__index__pb2.RequestToIndex.SerializeToString,
            grpc__change__index__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
