# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_change_index.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17grpc_change_index.proto\x12\x14\x62\x61rband_change_index\"\x87\x01\n\tEventInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x12\n\ncategories\x18\x06 \x03(\t\x12\x16\n\x0e\x63\x61tegory_level\x18\x07 \x03(\x05\"s\n\x0eRequestToIndex\x12/\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1f.barband_change_index.EventInfo\x12\x30\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32 .barband_change_index.ChangeType\" \n\x08Response\x12\x14\n\x0c\x45rrorMessage\x18\x01 \x01(\t*%\n\x0eResponseStatus\x12\x0b\n\x07\x43RASHED\x10\x00\x12\x06\n\x02OK\x10\x01*-\n\nChangeType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\n\n\x06UPDATE\x10\x02\x32]\n\x0b\x43hangeIndex\x12N\n\x06\x43hange\x12$.barband_change_index.RequestToIndex\x1a\x1e.barband_change_index.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_change_index_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSESTATUS']._serialized_start=338
  _globals['_RESPONSESTATUS']._serialized_end=375
  _globals['_CHANGETYPE']._serialized_start=377
  _globals['_CHANGETYPE']._serialized_end=422
  _globals['_EVENTINFO']._serialized_start=50
  _globals['_EVENTINFO']._serialized_end=185
  _globals['_REQUESTTOINDEX']._serialized_start=187
  _globals['_REQUESTTOINDEX']._serialized_end=302
  _globals['_RESPONSE']._serialized_start=304
  _globals['_RESPONSE']._serialized_end=336
  _globals['_CHANGEINDEX']._serialized_start=424
  _globals['_CHANGEINDEX']._serialized_end=517
# @@protoc_insertion_point(module_scope)
