# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recomendation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13recomendation.proto\x12\x17\x62\x61rband_recommendations\")\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\teventsIds\x18\x02 \x03(\x05\"\x1f\n\nRecForUser\x12\x11\n\teventsIds\x18\x03 \x03(\x05\x32o\n\x12getRecommendations\x12Y\n\x0fRecommendations\x12!.barband_recommendations.UserInfo\x1a#.barband_recommendations.RecForUserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recomendation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERINFO']._serialized_start=48
  _globals['_USERINFO']._serialized_end=89
  _globals['_RECFORUSER']._serialized_start=91
  _globals['_RECFORUSER']._serialized_end=122
  _globals['_GETRECOMMENDATIONS']._serialized_start=124
  _globals['_GETRECOMMENDATIONS']._serialized_end=235
# @@protoc_insertion_point(module_scope)
