# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import recomendation_pb2 as recomendation__pb2


class getRecommendationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommendations = channel.unary_unary(
                '/barband_recommendations.getRecommendations/Recommendations',
                request_serializer=recomendation__pb2.UserInfo.SerializeToString,
                response_deserializer=recomendation__pb2.RecForUser.FromString,
                )


class getRecommendationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Recommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getRecommendationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommendations,
                    request_deserializer=recomendation__pb2.UserInfo.FromString,
                    response_serializer=recomendation__pb2.RecForUser.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barband_recommendations.getRecommendations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class getRecommendations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Recommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/barband_recommendations.getRecommendations/Recommendations',
            recomendation__pb2.UserInfo.SerializeToString,
            recomendation__pb2.RecForUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
